version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./app/data:/app/data
      - ./app/logs:/app/logs
      - ./app/backups:/app/backups
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app:create_app()
      - SECRET_KEY=${SECRET_KEY:-default_dev_key}
      - DATABASE_URL=sqlite:////app/data/nfl_pickems.db
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONPATH=/app/backend
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://192.168.1.158:5000
      - CHOKIDAR_USEPOLLING=true
      - WDS_SOCKET_PORT=0
    command: npm start
    depends_on:
      - backend
    restart: unless-stopped
