"""Initial migration

Revision ID: 001
Revises: 
Create Date: 2023-11-14 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=80), nullable=False),
        sa.Column('password_hash', sa.String(length=120), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=True),
        sa.Column('first_login', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('username')
    )
    op.create_table('game',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('espn_id', sa.String(length=20), nullable=True),
        sa.Column('week', sa.Integer(), nullable=True),
        sa.Column('home_team', sa.String(length=50), nullable=True),
        sa.Column('away_team', sa.String(length=50), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('is_mnf', sa.Boolean(), nullable=True),
        sa.Column('final_score_home', sa.Integer(), nullable=True),
        sa.Column('final_score_away', sa.Integer(), nullable=True),
        sa.Column('winner', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('espn_id')
    )
    op.create_table('pick',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('game_id', sa.Integer(), nullable=False),
        sa.Column('picked_team', sa.String(length=50), nullable=True),
        sa.Column('week', sa.Integer(), nullable=True),
        sa.Column('mnf_total_points', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick')
    op.drop_table('game')
    op.drop_table('user')
    # ### end Alembic commands ###
